### ISSUE TITLE
Make possible to change a service name in a update

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNodeSDK#174]
**Describe the bug**

Modifying a service of a package and make an update provokes an error on the packages in the dappmanager. The package works but not correctly. It's waiting for the old name service.

**To Reproduce**

1. Install a package
2.  Go to docker-compose and modify the name of the service and the place where is needed
3. dappnodesdk build and update the package
4. See error-->

**Expected behaviour**

Go to reports and check if there is an error.

**Additional context**

```
Reply: No service bee.dnp.dappnode.eth in dnp bee.dnp.dappnode.eth
Error: No service bee.dnp.dappnode.eth in dnp bee.dnp.dappnode.eth
    at /usr/src/app/webpack:/src/calls/packageSetEnvironment.ts:28:25
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/index.js:66678:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

{
  "dnpName": "bee.dnp.dappnode.eth",
  "environmentByService": {
    "node": {
      "PASSWORD": "**********",
      "EXTRA_OPTS": "full-node"
    },
    "bee.dnp.dappnode.eth": {
      "PASSWORD": "**********",
      "BEE_SWAP_ENDPOINT": "http://goerli-geth.dappnode:8545",
      "BEE_DB_CAPACITY": "5000000",
      "BEE_WELCOME_MESSAGE": "Hello from my DAppNode!"
    }
  }
}
```

**Comment by tropicar** [comment]
I tried to replicate the error, even with the same package and now the error does not appear, i am sure why. I tried to force it, creating a new package and update modifying the service name but i could not force this error appear.
