### ISSUE TITLE
Error: Unexpected resulting architecture: x86_64

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodeSDK#182]
## Context
DAppNode packages main workflows ([an example](https://github.com/dappnode/DAppNodePackage-geth/blob/master/.github/workflows/main.yml)) uses the SDK to check for new upstream versions, and compiles and uploads the new DAppNode package version if necessary.

This bug is preventing from creating the comment with the IPFS hash to test the package

## Error
This check may fail if the architecture is not the expected with the error:
```
Error: Unexpected resulting architecture: x86_64
    at Object.<anonymous> (/home/runner/.npm/_npx/1566/lib/node_modules/@dappnode/dappnodesdk/src/tasks/buildWithBuildx.ts:98:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/.npm/_npx/1566/lib/node_modules/@dappnode/dappnodesdk/dist/tasks/buildWithBuildx.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
Examples of the failing workflow: 
- [Error in geth](https://github.com/dappnode/DAppNodePackage-geth/runs/3951472356?check_suite_focus=true)
- [Error in rinkeby](https://github.com/dappnode/DAppNodePackage-rinkeby/runs/3953926076?check_suite_focus=true)

Source code:
- [Throw error](https://github.com/dappnode/DAppNodeSDK/blob/55d714e825961f3d3c07af98daad53c70113a922/src/tasks/saveAndCompressImages.ts#L57)
- [Architecture types](https://github.com/dappnode/DAppNodeSDK/blob/55d714e825961f3d3c07af98daad53c70113a922/src/types.ts#L27)

**Comment by FAvE01** [comment]
``

**Comment by FAvE01** [comment]
- [ ] 
![Uploading A592F3BD-9C63-4355-B553-35540703B058.jpeg…]()

**Comment by FAvE01** [comment]
![Uploading D4C60A99-2598-4E7D-9EA0-D905A1C562E4.png…]()

**Comment by FAvE01** [comment]
![Uploading DA1BB923-8557-4206-9030-EAF5D4598459.jpeg…]()

**Comment by pablomendezroyo** [comment]
Seems to be an error that happens randomly. Eventually, a few gha fails so the ipfs hash is not generated, re-running the gha passes the check some times
