### ISSUE TITLE
Provide a better error message if docker-compose is missing.

### ISSUE THREAD

**Issue by cburgdorf** [dappnode/DAppNodeSDK#39]
## What's wrong

Currently, if `docker-compose` is missing the error is:

```shell
$ dappnodesdk build
TypeError: Cannot create property 'context' on string '/bin/sh: 1: docker-compose: not found'
    at tasks.then.catch.error (/home/cburgdorf/.config/yarn/global/node_modules/listr/index.js:112:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## How to fix it

Catch the error and provide a useful message to the user

**Comment by dapplion** [comment]
Thanks for reporting! Already fix in current released version
