### ISSUE TITLE
Error creating next version branch

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DAppNodeSDK#61]
Running publish with --dappnode_team_preset through an error when the sdk tries to create the next version branch

```
dappnodesdk publish patch -a 0xF35960302a07022aBa880DFFaEC2Fdd64d5BF1c1 --dappnode_team_preset
Assuming directory type release
  ✔ Fetch current version from APM (next version: 0.1.1)
  ✔ Build and upload
  ✔ Generate transaction
  ❯ Release on github
    ✔ Handle tags
    ✔ Create release
    ⠴ Upload release assets
      → Uploading /Users/edu/DAppNodePackages/DAppNodePackage-trustlines-netstats/build_0.1.1/trustlines-netstats.dnp.dappnode.eth_0.1.1.tar.xz...
      Create next version branch











Error creating next version branch:
Error: Variable manifest image must be defined
    at check (/Users/edu/DAppNodePackages/DAppNodeSDK/src/utils/check.js:3:11)
    at increaseFromLocalVersion (/Users/edu/DAppNodePackages/DAppNodeSDK/src/utils/versions/increaseFromLocalVersion.js:16:3)
    at Task.task (/Users/edu/DAppNodePackages/DAppNodeSDK/src/tasks/createGithubRelease.js:264:39)
    at Promise.resolve.then.then.skipped (/Users/edu/DAppNodePackages/DAppNodeSDK/node_modules/listr/lib/task.js:167:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)


  ✔ Fetch current version from APM (next version: 0.1.1)
  ✔ Build and upload
  ✔ Generate transaction
  ✔ Release on github

  DNP (DAppNode Package) published (version 0.1.1) 
  Manifest hash : /ipfs/QmRNCEHh7SK2o97UphGaqyaiUkpqg23CYxVNUJNYVWuNne
  Install link : http://my.dappnode/#/installer/%2Fipfs%2FQmRNCEHh7SK2o97UphGaqyaiUkpqg23CYxVNUJNYVWuNne

  You must execute this transaction in mainnet to publish a new version of this DNP.
  
  To    : 0xcc9a190e06531bd6a68ce14e2e2a87f75bfe473f
  Value : 0
  Data  : 0x73053410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000342f697066732f516d524e4345486837534b326f3937557068476171796169556b7071673233435978564e554a4e595657754e6e65000000000000000000000000
  Gas   : 300000

  You can also execute this transaction with Metamask by following this pre-filled link
  
  http://my.dappnode/#/sdk/publish/r=trustlines-netstats.dnp.dappnode.eth&v=0.1.1&h=%2Fipfs%2FQmRNCEHh7SK2o97UphGaqyaiUkpqg23CYxVNUJNYVWuNne
```

**Comment by dapplion** [comment]
Outdated
